In [1]:
import numpy as np

In [10]:
rows = 2
cols = 2
a = np.mgrid[0:rows, 0:cols, 0:3]

In [11]:
print(a.shape)
a

(3, 2, 2, 3)


array([[[[0, 0, 0],
         [0, 0, 0]],

        [[1, 1, 1],
         [1, 1, 1]]],


       [[[0, 0, 0],
         [1, 1, 1]],

        [[0, 0, 0],
         [1, 1, 1]]],


       [[[0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2]]]])

In [12]:
a.T

array([[[[0, 0, 0],
         [1, 0, 0]],

        [[0, 1, 0],
         [1, 1, 0]]],


       [[[0, 0, 1],
         [1, 0, 1]],

        [[0, 1, 1],
         [1, 1, 1]]],


       [[[0, 0, 2],
         [1, 0, 2]],

        [[0, 1, 2],
         [1, 1, 2]]]])

In [14]:
newa = a.T.reshape(-1, 1, 3)
print(newa.shape)
print(newa)

(12, 1, 3)
[[[0 0 0]]

 [[1 0 0]]

 [[0 1 0]]

 [[1 1 0]]

 [[0 0 1]]

 [[1 0 1]]

 [[0 1 1]]

 [[1 1 1]]

 [[0 0 2]]

 [[1 0 2]]

 [[0 1 2]]

 [[1 1 2]]]


In [7]:
objectPoints = np.zeros((rows * cols, 1, 3), np.float32)
objectPoints[:, :, :2] = np.mgrid[0:rows, 0:cols].T.reshape(-1, 1, 2)
print(objectPoints)

[[[0. 0. 0.]]

 [[1. 0. 0.]]

 [[0. 1. 0.]]

 [[1. 1. 0.]]]


In [8]:
objectPoints.shape

(4, 1, 3)

In [17]:
newa = newa.reshape(-1, 4, 3)
newa.shape

(3, 4, 3)